//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatOpcionesChn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatOpcionesChn()
        {
            this.TblDeclaracionSaludlg = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg1 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg2 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg3 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg4 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg5 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg6 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg7 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg8 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg9 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg10 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg11 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg12 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg13 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg14 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg15 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg16 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg17 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg18 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg19 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg20 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg21 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg22 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg23 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg24 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg25 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg26 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg27 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg28 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg29 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg30 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg31 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg32 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg33 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg34 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg35 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg36 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg37 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg38 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg39 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg40 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg41 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg42 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg43 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg44 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg45 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg46 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg47 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg48 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg49 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg50 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg51 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg52 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg53 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlg54 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludchnlg = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg1 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg2 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg3 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg4 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg5 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg6 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg7 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg8 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg9 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg10 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg11 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg12 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg13 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg14 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg15 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg16 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg17 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg18 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg19 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg20 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg21 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg22 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg23 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg24 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg25 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg26 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg27 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg28 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg29 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg30 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg31 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg32 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg33 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg34 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg35 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg36 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg37 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg38 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg39 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg40 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg41 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg42 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg43 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg44 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg45 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg46 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg47 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg48 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg49 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg50 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg51 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg52 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlg53 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSalud = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud1 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud2 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud3 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud4 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud5 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud6 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud7 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud8 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud9 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud10 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud11 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud12 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud13 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud14 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud15 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud16 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud17 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud18 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud19 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud20 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud21 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud22 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud23 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud24 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud25 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud26 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud27 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud28 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud29 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud30 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud31 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud32 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud33 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud34 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud35 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud36 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud37 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud38 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud39 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud40 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud41 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud42 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud43 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud44 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud45 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud46 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud47 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud48 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud49 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud50 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud51 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud52 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud53 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud54 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud55 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSalud56 = new HashSet<TblDeclaracionSalud>();
        }
    
        public long idCatOpcionesChn { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg35 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg36 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg37 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg42 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg44 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg45 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg47 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg49 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg52 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg53 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlg54 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg35 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg36 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg37 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg42 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg44 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg45 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg47 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg49 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg52 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg53 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud35 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud36 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud37 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud42 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud44 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud45 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud47 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud49 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud52 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud53 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud54 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud55 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud56 { get; set; }
    }
}
