//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class constanciasLaborales
    {
        public long idConstancias { get; set; }
        public Nullable<long> idAgencias { get; set; }
        public string otroDestino { get; set; }
        public string fechaEmision { get; set; }
        public string codigoEmpleado { get; set; }
        public string nombreCompleto { get; set; }
        public string dpi { get; set; }
        public string inicioLabores { get; set; }
        public string puesto { get; set; }
        public Nullable<decimal> salarioBase { get; set; }
        public Nullable<decimal> bonificacionesLey { get; set; }
        public Nullable<System.DateTime> fechahoraCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> keyConstancia { get; set; }
        public Nullable<long> idCatEstatosRrhh { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public string comentarioRrhh { get; set; }
        public Nullable<long> idCatGeneros { get; set; }
    
        public virtual TblUsuarios TblUsuarios { get; set; }
        public virtual CatEstados CatEstados { get; set; }
        public virtual CatSexo CatSexo { get; set; }
        public virtual CatUbicaciones CatUbicaciones { get; set; }
        public virtual CatEstadosRrhh CatEstadosRrhh { get; set; }
    }
}
