//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersInformations
    {
        public long idTblCustomersInformations { get; set; }
        public string bodyId { get; set; }
        public string recordSequenceNumber { get; set; }
        public string nuevoCif { get; set; }
        public string multiCreditCif { get; set; }
        public string cardHolderType { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public string thirdName { get; set; }
        public string customerSinceDate { get; set; }
        public string address1A { get; set; }
        public string telephone1 { get; set; }
        public Nullable<int> languageCode { get; set; }
        public Nullable<int> mailinOption { get; set; }
        public string dateOfBirth { get; set; }
        public string gender { get; set; }
        public string martialStatus { get; set; }
        public string idCardNumber { get; set; }
        public string emailAddress { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    }
}
