//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAsambleas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAsambleas()
        {
            this.TblAsistenciasAsambaleas = new HashSet<TblAsistenciasAsambaleas>();
        }
    
        public long idTblAsambleas { get; set; }
        public Nullable<long> idCatAnios { get; set; }
        public Nullable<long> idCatMeses { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<int> extraordinaria { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual CatAnios CatAnios { get; set; }
        public virtual CatEstados CatEstados { get; set; }
        public virtual CatMeses CatMeses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambaleas> TblAsistenciasAsambaleas { get; set; }
    }
}
