//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAccountInformation
    {
        public long idTblAccountInformation { get; set; }
        public string bodyId { get; set; }
        public string recordSequenceNumber { get; set; }
        public string cif { get; set; }
        public string accountNumber { get; set; }
        public string cardAccountNumberBase { get; set; }
        public string accountStatus { get; set; }
        public string dateStatusArchived { get; set; }
        public string accountOpeningDate { get; set; }
        public string lastActivityDate { get; set; }
        public string accountHolderType { get; set; }
        public string accountBranch { get; set; }
        public string reportingBranch { get; set; }
        public string accountProductNumber { get; set; }
        public Nullable<int> baseCurrency { get; set; }
        public string ledgerBalance { get; set; }
        public string statementDay { get; set; }
        public string currentStatementDay { get; set; }
        public string primaryLoc { get; set; }
        public string openToBuy { get; set; }
        public string lastCutOffBalance { get; set; }
        public string withdrawAvailable { get; set; }
        public string minimumPayment { get; set; }
        public string paymentDueDate { get; set; }
        public Nullable<int> statementOption { get; set; }
        public Nullable<int> preApprovePaymentPAPOption { get; set; }
        public string preApprovePaymentAmount { get; set; }
        public string preApprovePaymentInstitution { get; set; }
        public string preApprovePaymentBranch { get; set; }
        public string preApprovePaymentAccountNumber { get; set; }
        public Nullable<long> idUsuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaHoraAlta { get; set; }
    }
}
