//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConsultasChatbot
    {
        public long idTblConsultasChatbot { get; set; }
        public Nullable<long> idCatTiposConsultasChatbot { get; set; }
        public string dpi { get; set; }
        public string complemento { get; set; }
        public Nullable<System.DateTime> fechaHoraConsulta { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> fechaEnvioToken { get; set; }
        public Nullable<System.DateTime> fechaExpiraToken { get; set; }
        public string telefonoEnvioToken { get; set; }
        public string jsonRequest { get; set; }
        public string jsonResponse { get; set; }
        public string jsonRequestAut { get; set; }
        public string jsonResponseAut { get; set; }
        public Nullable<long> idTblUsuariosWebApi { get; set; }
    
        public virtual CatTiposConsultasChatbot CatTiposConsultasChatbot { get; set; }
    }
}
