//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConsultasIPass
    {
        public long idTblConsultasIPass { get; set; }
        public string codigoDeAsociado { get; set; }
        public string tipoDocumento { get; set; }
        public string numeroDoc { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string tercerNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string apellidoCasada { get; set; }
        public string fechaNacimiento { get; set; }
        public string nacionalidad { get; set; }
        public string genero { get; set; }
        public string estadoCivil { get; set; }
        public string expiracion { get; set; }
        public string paisNacimiento { get; set; }
        public Nullable<int> layer3 { get; set; }
        public string trNumDocumento { get; set; }
        public Nullable<decimal> trc2 { get; set; }
        public Nullable<decimal> trc3 { get; set; }
        public Nullable<decimal> tr { get; set; }
        public string trClasificacion { get; set; }
        public string trEstatus { get; set; }
        public Nullable<int> trSuccess { get; set; }
        public string trMessage { get; set; }
        public string numDocumento { get; set; }
        public string fechaNacimientoCA { get; set; }
        public string fechaNacimientoCB { get; set; }
        public Nullable<decimal> fechaNacimientoTr { get; set; }
        public string paisNacimientoCB { get; set; }
        public string paisNacimientoCA { get; set; }
        public Nullable<decimal> paisNacimientoTr { get; set; }
        public string nacionalidadCB { get; set; }
        public string nacionalidadCA { get; set; }
        public Nullable<decimal> nacionalidadTr { get; set; }
        public string primerNombreCB { get; set; }
        public string primerNombreCA { get; set; }
        public Nullable<decimal> primerNombreTr { get; set; }
        public string segundoNombreCB { get; set; }
        public string segundoNombreCA { get; set; }
        public Nullable<decimal> segundoNombreTr { get; set; }
        public string tercerNombreCB { get; set; }
        public string tercerNombreCA { get; set; }
        public Nullable<decimal> tercerNombreTr { get; set; }
        public string primerApellidoCB { get; set; }
        public string primerApellidoCA { get; set; }
        public Nullable<decimal> primerApellidoTr { get; set; }
        public string segundoApellidoCB { get; set; }
        public string segundoApellidoCA { get; set; }
        public Nullable<decimal> segundoApellidoTr { get; set; }
        public string estadoCivilCB { get; set; }
        public string estadoCivilCA { get; set; }
        public Nullable<decimal> estadoCivilTr { get; set; }
        public string apellidoCasadaCB { get; set; }
        public string apellidoCasadaCA { get; set; }
        public Nullable<decimal> apellidoCasadaTr { get; set; }
        public string jsonRequest { get; set; }
        public string jsonResponse { get; set; }
        public Nullable<long> idTblUsuariosConsultas { get; set; }
        public Nullable<System.DateTime> fechaConsulta { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idSucursal { get; set; }
        public Nullable<int> asociado { get; set; }
        public Nullable<int> griError { get; set; }
    
        public virtual TblUsuarios TblUsuarios { get; set; }
        public virtual CatEstados CatEstados { get; set; }
    }
}
