//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCardsInformations
    {
        public long idTblCardsInformations { get; set; }
        public string bodyId { get; set; }
        public string record { get; set; }
        public string cif { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> cardStatus { get; set; }
        public string dateStatusArchieved { get; set; }
        public Nullable<int> cardTrackingStatus { get; set; }
        public Nullable<int> numberOfTimesPinRetry { get; set; }
        public Nullable<int> cardProductNumber { get; set; }
        public string cardHolderType { get; set; }
        public Nullable<int> accountBranch { get; set; }
        public Nullable<int> reportingBranch { get; set; }
        public string primaryAdditionalCardIndicator { get; set; }
        public string primaryCardNumber { get; set; }
        public string dateOnWhichTheCardWasIssuedFirst { get; set; }
        public string expiryDate { get; set; }
        public string nextMembershipFeeAmount { get; set; }
        public string cardholderNameOnCard { get; set; }
        public string companyNameOnCard { get; set; }
        public string primaryCif { get; set; }
        public string cardIssueDate { get; set; }
        public string addressLine1 { get; set; }
        public string telephone { get; set; }
        public string cvv { get; set; }
        public string cvv2 { get; set; }
        public string pvv { get; set; }
        public string epin { get; set; }
        public Nullable<long> idTblUsuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    }
}
