//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCuentasAsociados
    {
        public long idTblCuentasAsociados { get; set; }
        public string cardNumber { get; set; }
        public string codigoAsociado { get; set; }
        public string cifNumber { get; set; }
        public string nombreCompleto { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string tercerNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string address1 { get; set; }
        public string emailAddress { get; set; }
        public string dateOfBirth { get; set; }
        public string gender { get; set; }
        public string martialStatus { get; set; }
        public string cardHolderNameOnCard { get; set; }
        public string ledgerBalanceGTQ { get; set; }
        public string minimumPaymentGTQ { get; set; }
        public string ledgerBalanceUSD { get; set; }
        public string minimumPaymentUSD { get; set; }
        public string customerSinceDate { get; set; }
        public string accountStatus { get; set; }
        public string primaryLocGTQ { get; set; }
        public string primaryLocUSD { get; set; }
        public string idCardNumber { get; set; }
        public string openToBuyGTQ { get; set; }
        public string openToBuyUSD { get; set; }
        public string telephone1 { get; set; }
        public string lastCutOffBalance_GTQ { get; set; }
        public string lastCutOffBalanceUSD { get; set; }
        public string withdrawAvailableGTQ { get; set; }
        public string withdrawAvailable_USD { get; set; }
        public string fechaVencimiento { get; set; }
        public string nextMembershipFeeAmount { get; set; }
        public string paymentDueDate { get; set; }
        public string currentStatementDate { get; set; }
        public string statementDay { get; set; }
        public string cardNumber2 { get; set; }
        public string estadoPlastico { get; set; }
        public string cardStatus { get; set; }
        public string primaryAdditionalCardIndicator { get; set; }
        public string primaryCardNumber { get; set; }
        public string lastActivityDate { get; set; }
        public string dateStatusArchived { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idUsuarioAlta { get; set; }
    }
}
