//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSolicitudesMoviemientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSolicitudesMoviemientos()
        {
            this.TblSolicitudesMovimientosDetalle = new HashSet<TblSolicitudesMovimientosDetalle>();
        }
    
        public long idTblSolicitudesMoviemientos { get; set; }
        public Nullable<long> idTblSolicitudesCooitzas { get; set; }
        public Nullable<long> idCatProveedoresCooitzas { get; set; }
        public Nullable<long> idCatEstadoSolicitudes { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<long> idTblUsuariosAlta { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuariosModifica { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string descripcion { get; set; }
    
        public virtual TblUsuarios TblUsuarios { get; set; }
        public virtual CatEstados CatEstados { get; set; }
        public virtual CatEstadoSolicitudes CatEstadoSolicitudes { get; set; }
        public virtual CatProveedoresCooitzas CatProveedoresCooitzas { get; set; }
        public virtual TblSolicitudesCooitzas TblSolicitudesCooitzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesMovimientosDetalle> TblSolicitudesMovimientosDetalle { get; set; }
    }
}
