//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSistemasCorreosDestinatariosCorreos
    {
        public long idTblSistemasCorreosDestinatariosCorreos { get; set; }
        public Nullable<long> idCatSistemasCorreos { get; set; }
        public Nullable<long> idCatDestinatariosCorreos { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual TblUsuarios TblUsuarios { get; set; }
        public virtual TblUsuarios TblUsuarios1 { get; set; }
        public virtual CatDestinatariosCorreos CatDestinatariosCorreos { get; set; }
        public virtual CatSistemasCorreos CatSistemasCorreos { get; set; }
        public virtual CatEstados CatEstados { get; set; }
    }
}
