//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImixWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUsuarios()
        {
            this.TblAsistenciasAsambaleas = new HashSet<TblAsistenciasAsambaleas>();
            this.TblAsistenciasAsambaleas1 = new HashSet<TblAsistenciasAsambaleas>();
            this.Tbl_U_Roles = new HashSet<Tbl_U_Roles>();
            this.TblBitacoraBusquedaUsuarios = new HashSet<TblBitacoraBusquedaUsuarios>();
            this.TblModulos = new HashSet<TblModulos>();
            this.TblModulos1 = new HashSet<TblModulos>();
            this.TblSubModulos = new HashSet<TblSubModulos>();
            this.CatBancos = new HashSet<CatBancos>();
            this.CatDestinatariosCorreo = new HashSet<CatDestinatariosCorreo>();
            this.CatDestinatariosCorreo1 = new HashSet<CatDestinatariosCorreo>();
            this.CatDestinatariosCorreos = new HashSet<CatDestinatariosCorreos>();
            this.CatDestinatariosCorreos1 = new HashSet<CatDestinatariosCorreos>();
            this.CatDestinatariosSms = new HashSet<CatDestinatariosSms>();
            this.CatDestinatariosSms1 = new HashSet<CatDestinatariosSms>();
            this.CatEstadosLoginRch = new HashSet<CatEstadosLoginRch>();
            this.CatEstadosLoginRch1 = new HashSet<CatEstadosLoginRch>();
            this.CatEstadoSolicitudes = new HashSet<CatEstadoSolicitudes>();
            this.CatHorarioServicios = new HashSet<CatHorarioServicios>();
            this.CatHorarioServicios1 = new HashSet<CatHorarioServicios>();
            this.CatImagenesIntranet = new HashSet<CatImagenesIntranet>();
            this.CatProveedoresCooitzas = new HashSet<CatProveedoresCooitzas>();
            this.CatProveedoresExternos = new HashSet<CatProveedoresExternos>();
            this.CatProveedoresExternos1 = new HashSet<CatProveedoresExternos>();
            this.CatPuestos = new HashSet<CatPuestos>();
            this.CatPuestos1 = new HashSet<CatPuestos>();
            this.CatServiciosMonitor = new HashSet<CatServiciosMonitor>();
            this.CatServiciosMonitor1 = new HashSet<CatServiciosMonitor>();
            this.CatSistemasCorreos = new HashSet<CatSistemasCorreos>();
            this.CatSistemasCorreos1 = new HashSet<CatSistemasCorreos>();
            this.CatTipificacionProductos = new HashSet<CatTipificacionProductos>();
            this.CatTipificacionProductos1 = new HashSet<CatTipificacionProductos>();
            this.CatTiposCuentas = new HashSet<CatTiposCuentas>();
            this.CatTiposCuentas1 = new HashSet<CatTiposCuentas>();
            this.CatTiposCuentas2 = new HashSet<CatTiposCuentas>();
            this.CatTiposEmpresasProveedores = new HashSet<CatTiposEmpresasProveedores>();
            this.CatTiposEmpresasProveedores1 = new HashSet<CatTiposEmpresasProveedores>();
            this.CatTiposKilometraje1 = new HashSet<CatTiposKilometraje1>();
            this.CatTiposKilometraje11 = new HashSet<CatTiposKilometraje1>();
            this.CatTiposMonedas = new HashSet<CatTiposMonedas>();
            this.CatTiposMovimientos = new HashSet<CatTiposMovimientos>();
            this.CatTiposProveedores = new HashSet<CatTiposProveedores>();
            this.CatTiposProveedores1 = new HashSet<CatTiposProveedores>();
            this.constanciasLaborales = new HashSet<constanciasLaborales>();
            this.TblAsignaciones = new HashSet<TblAsignaciones>();
            this.TblAsignacionesEjecutivosSucursales = new HashSet<TblAsignacionesEjecutivosSucursales>();
            this.tblbitacorapremora = new HashSet<tblbitacorapremora>();
            this.TblBitacoraService = new HashSet<TblBitacoraService>();
            this.TblCarteraCredito = new HashSet<TblCarteraCredito>();
            this.TblCertificacionesTecnicos = new HashSet<TblCertificacionesTecnicos>();
            this.TblCertificacionesTecnicos1 = new HashSet<TblCertificacionesTecnicos>();
            this.TblCierresProductos = new HashSet<TblCierresProductos>();
            this.TblCierresProductos1 = new HashSet<TblCierresProductos>();
            this.TblConfiguracionesRch = new HashSet<TblConfiguracionesRch>();
            this.TblConfiguracionesRch1 = new HashSet<TblConfiguracionesRch>();
            this.TblDeclaracionSalud = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaludchnlg = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDirectorios = new HashSet<TblDirectorios>();
            this.TblDirectorios1 = new HashSet<TblDirectorios>();
            this.TblEmpleadosMetas = new HashSet<TblEmpleadosMetas>();
            this.TblEmpleadosMetas1 = new HashSet<TblEmpleadosMetas>();
            this.TblEmpleadosMetas2 = new HashSet<TblEmpleadosMetas>();
            this.TblEntregas = new HashSet<TblEntregas>();
            this.TblEstado_Solicitudes = new HashSet<TblEstado_Solicitudes>();
            this.TblEstado_Solicitudes1 = new HashSet<TblEstado_Solicitudes>();
            this.TblGirasTecnicos = new HashSet<TblGirasTecnicos>();
            this.TblGirasTecnicos1 = new HashSet<TblGirasTecnicos>();
            this.TblGirasTecnicos2 = new HashSet<TblGirasTecnicos>();
            this.TblGirasTecnicos3 = new HashSet<TblGirasTecnicos>();
            this.TblGruposAgencias = new HashSet<TblGruposAgencias>();
            this.TblGruposAgencias1 = new HashSet<TblGruposAgencias>();
            this.TblHistoriales1 = new HashSet<TblHistoriales1>();
            this.TblMigracion = new HashSet<TblMigracion>();
            this.TblMigracion1 = new HashSet<TblMigracion>();
            this.TblMonitorGrabacion = new HashSet<TblMonitorGrabacion>();
            this.tblpremora = new HashSet<tblpremora>();
            this.tblpremora1 = new HashSet<tblpremora>();
            this.TblProductosCooitza = new HashSet<TblProductosCooitza>();
            this.TblProductosCooitza1 = new HashSet<TblProductosCooitza>();
            this.TblSistemasCorreosDestinatariosCorreos = new HashSet<TblSistemasCorreosDestinatariosCorreos>();
            this.TblSistemasCorreosDestinatariosCorreos1 = new HashSet<TblSistemasCorreosDestinatariosCorreos>();
            this.TblSolicitudes = new HashSet<TblSolicitudes>();
            this.TblSolicitudes1 = new HashSet<TblSolicitudes>();
            this.TblSolicitudesCooitzas = new HashSet<TblSolicitudesCooitzas>();
            this.TblSolicitudesMoviemientos = new HashSet<TblSolicitudesMoviemientos>();
            this.TblSolicitudesMovimientosDetalle = new HashSet<TblSolicitudesMovimientosDetalle>();
            this.TblSucrusalesProductosCooitza = new HashSet<TblSucrusalesProductosCooitza>();
            this.TblSucrusalesProductosCooitza1 = new HashSet<TblSucrusalesProductosCooitza>();
            this.TblUsuarios_Coordinador = new HashSet<TblUsuarios_Coordinador>();
            this.TblUsuarios_Coordinador1 = new HashSet<TblUsuarios_Coordinador>();
            this.TblUsuarios_Coordinador2 = new HashSet<TblUsuarios_Coordinador>();
            this.TblUsuarios_Coordinador3 = new HashSet<TblUsuarios_Coordinador>();
            this.TransaccionesImix = new HashSet<TransaccionesImix>();
        }
    
        public long idTblUsuarios { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string token { get; set; }
        public string email { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFinal { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblPersonas { get; set; }
        public Nullable<long> idCatOpciones { get; set; }
        public Nullable<long> idCatDepartamentosTrabajo { get; set; }
        public Nullable<long> idCodigoJefe { get; set; }
        public Nullable<long> idCodigoGerenete { get; set; }
        public Nullable<long> idCatUbicaciones { get; set; }
        public Nullable<long> IdCore { get; set; }
        public Nullable<long> IdEmpleadoCore { get; set; }
        public string imagenCore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambaleas> TblAsistenciasAsambaleas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambaleas> TblAsistenciasAsambaleas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_U_Roles> Tbl_U_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBitacoraBusquedaUsuarios> TblBitacoraBusquedaUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblModulos> TblModulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblModulos> TblModulos1 { get; set; }
        public virtual TblPersonas TblPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubModulos> TblSubModulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatBancos> CatBancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosCorreo> CatDestinatariosCorreo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosCorreo> CatDestinatariosCorreo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosCorreos> CatDestinatariosCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosCorreos> CatDestinatariosCorreos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosSms> CatDestinatariosSms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosSms> CatDestinatariosSms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadosLoginRch> CatEstadosLoginRch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadosLoginRch> CatEstadosLoginRch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadoSolicitudes> CatEstadoSolicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatHorarioServicios> CatHorarioServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatHorarioServicios> CatHorarioServicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatImagenesIntranet> CatImagenesIntranet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatProveedoresCooitzas> CatProveedoresCooitzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatProveedoresExternos> CatProveedoresExternos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatProveedoresExternos> CatProveedoresExternos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPuestos> CatPuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPuestos> CatPuestos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatServiciosMonitor> CatServiciosMonitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatServiciosMonitor> CatServiciosMonitor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatSistemasCorreos> CatSistemasCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatSistemasCorreos> CatSistemasCorreos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipificacionProductos> CatTipificacionProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipificacionProductos> CatTipificacionProductos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposCuentas> CatTiposCuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposCuentas> CatTiposCuentas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposCuentas> CatTiposCuentas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposEmpresasProveedores> CatTiposEmpresasProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposEmpresasProveedores> CatTiposEmpresasProveedores1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposKilometraje1> CatTiposKilometraje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposKilometraje1> CatTiposKilometraje11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposMonedas> CatTiposMonedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposMovimientos> CatTiposMovimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposProveedores> CatTiposProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposProveedores> CatTiposProveedores1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<constanciasLaborales> constanciasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsignaciones> TblAsignaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsignacionesEjecutivosSucursales> TblAsignacionesEjecutivosSucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbitacorapremora> tblbitacorapremora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBitacoraService> TblBitacoraService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCarteraCredito> TblCarteraCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCertificacionesTecnicos> TblCertificacionesTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCertificacionesTecnicos> TblCertificacionesTecnicos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCierresProductos> TblCierresProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCierresProductos> TblCierresProductos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblConfiguracionesRch> TblConfiguracionesRch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblConfiguracionesRch> TblConfiguracionesRch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDirectorios> TblDirectorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDirectorios> TblDirectorios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleadosMetas> TblEmpleadosMetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleadosMetas> TblEmpleadosMetas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleadosMetas> TblEmpleadosMetas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEntregas> TblEntregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEstado_Solicitudes> TblEstado_Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEstado_Solicitudes> TblEstado_Solicitudes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGirasTecnicos> TblGirasTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGirasTecnicos> TblGirasTecnicos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGirasTecnicos> TblGirasTecnicos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGirasTecnicos> TblGirasTecnicos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGruposAgencias> TblGruposAgencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGruposAgencias> TblGruposAgencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHistoriales1> TblHistoriales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMigracion> TblMigracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMigracion> TblMigracion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMonitorGrabacion> TblMonitorGrabacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpremora> tblpremora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpremora> tblpremora1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductosCooitza> TblProductosCooitza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductosCooitza> TblProductosCooitza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSistemasCorreosDestinatariosCorreos> TblSistemasCorreosDestinatariosCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSistemasCorreosDestinatariosCorreos> TblSistemasCorreosDestinatariosCorreos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudes> TblSolicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudes> TblSolicitudes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesCooitzas> TblSolicitudesCooitzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesMoviemientos> TblSolicitudesMoviemientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesMovimientosDetalle> TblSolicitudesMovimientosDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSucrusalesProductosCooitza> TblSucrusalesProductosCooitza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSucrusalesProductosCooitza> TblSucrusalesProductosCooitza1 { get; set; }
        public virtual CatDepartamentosTrabajo CatDepartamentosTrabajo { get; set; }
        public virtual CatEstados CatEstados { get; set; }
        public virtual CatOpciones CatOpciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios_Coordinador> TblUsuarios_Coordinador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios_Coordinador> TblUsuarios_Coordinador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios_Coordinador> TblUsuarios_Coordinador2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios_Coordinador> TblUsuarios_Coordinador3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransaccionesImix> TransaccionesImix { get; set; }
    }
}
